pull_request_title: 'i18n: update translations'
pull_request_labels:
  - i18n
files:
  - source: /zh-CN/**/*.md
    translation: /%locale%/**/%file_name%.md
  - source: /.vitepress/config/zh-CN.json
    translation: /.vitepress/config/%locale%.json
